name: Dynamic - Security Pipeline

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: "URL to scan with ZAP"
        required: true
        default: "http://127.0.0.1:8000"
  workflow_call:
    inputs:
      target_url:
        description: "URL to scan with ZAP"
        required: true
        type: string

jobs:
  zap-full-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0

        with:
          target: ${{ github.event.inputs.target_url || inputs.target_url }}
          cmd_options: >-
            -m 5 -T 10
            -J reports/zap-report.json
          artifact_name: DAST-zap-full

      - name: Upload JSON report explicitly
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: DAST-zap-json
          path: reports/zap-report.json
