name: Dynamic - Security Pipeline

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: "URL to scan with ZAP"
        required: true
        default: "http://127.0.0.1:8000"

jobs:
  zap-baseline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0

        with:
          target: ${{ github.event.inputs.target_url }}
          cmd_options: '-a -m 5 -T 600'
          artifact_name: DAST-zap-full
