name: Static - Security Pipeline

on:
  workflow_dispatch:
    inputs:
      target_repo:
        description: "Git repository URL (e.g., https://github.com/flaskbb/flaskbb.git)"
        required: true
        default: "https://github.com/flaskbb/flaskbb.git"
      target_ref:
        description: "Branch/Tag/Commit of the target application (e.g., main)"
        required: false
        default: "master"
  workflow_call:
    inputs:
      target_repo:
        description: "Git repository URL (e.g., https://github.com/flaskbb/flaskbb.git)"
        required: true
        type: string
      target_ref:
        description: "Branch/Tag/Commit of the target application (e.g., main)"
        required: false
        type: string
  # push:
  #   branches: []

jobs:
  clone:
    name: Clone target repository
    runs-on: ubuntu-latest
    env:
      TARGET_REPO: ${{ inputs.target_repo || github.event.inputs.target_repo || 'https://github.com/flaskbb/flaskbb.git' }}
      TARGET_REF:  ${{ inputs.target_ref  || github.event.inputs.target_ref  || 'master' }}
      APP_DIR:     ${{ github.workspace }}/target-app
    steps:
      - name: Checkout (this delivery repo)
        uses: actions/checkout@v4

      - name: Clone target application (public repo only)
        run: |
          echo "Cloning ${TARGET_REPO} (ref: ${TARGET_REF}) into ${APP_DIR} ..."
          git clone --depth 1 --branch "${TARGET_REF}" "${TARGET_REPO}" "${APP_DIR}"

          echo "Clone completed. Top-level files:"
          ls -la "${APP_DIR}"

      - name: Upload target app as artifact
        uses: actions/upload-artifact@v4
        with:
          name: target-app
          path: target-app/
          retention-days: 7 

  sast:
    name: Static Analysis — SAST (Semgrep)
    runs-on: ubuntu-latest
    needs: clone
    steps:
      - name: Checkout (this delivery repo)
        uses: actions/checkout@v4

      - name: Download target app artifact
        uses: actions/download-artifact@v4
        with:
          name: target-app
          path: ./target-app

      - name: Prepare SAST folder
        run: mkdir -p SAST

      - name: Run Semgrep (official action)
        uses: semgrep/semgrep-action@v1
        with:
          entryPoint: semgrep
          args: >-
            --config p/security-audit
            --timeout 180
            --metrics=off
            --exclude node_modules --exclude venv --exclude .venv --exclude .git
            --json --output SAST/semgrep-report.json
            ./target-app
        continue-on-error: true

      - name: Upload SAST artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SAST-semgrep
          path: SAST/semgrep-report.json

  sca:
    name: Static Analysis — SCA (OSV-Scanner)
    runs-on: ubuntu-latest
    needs: clone
    steps:
      - name: Checkout (this delivery repo)
        uses: actions/checkout@v4

      - name: Download target app artifact
        uses: actions/download-artifact@v4
        with:
          name: target-app
          path: ./target-app

      - name: Install OSV-Scanner
        run: |
          curl -L https://github.com/google/osv-scanner/releases/latest/download/osv-scanner_linux_amd64 -o /usr/local/bin/osv-scanner
          chmod +x /usr/local/bin/osv-scanner

      - name: Run OSV-Scanner on repo
        working-directory: ./target-app
        run: |
          mkdir -p "$GITHUB_WORKSPACE/SCA"
          pwd
          ls -la
          osv-scanner scan --recursive . \
          --format json \
          --output "$GITHUB_WORKSPACE/SCA/osv-scanner-repo.json" || true

      - name: Upload SCA artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SCA-osv-scanner
          path: SCA/*
